apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
  namespace: "{{ .Release.Namespace }}"
data:
  config.json: |
    {{- pick .Values "kernel" "store" | toPrettyJson | nindent 4 }}
