image:
  repo: ghcr.io/digital-asset/wallet-gateway/docker
  tag: ""
# @schema $ref: ./config.schema.json
config:
  kernel:
    id: remote-da
    publicUrl: "https://wallet.example.com"
    clientType: remote
  server:
    port: 3030
    dappPath: "/api/v0/dapp"
    userPath: "/api/v0/user"
    allowedOrigins: "*"
    requestSizeLimit: "5mb"
    requestRateLimit: 100
  store:
    connection:
      type: sqlite
      database: store.sqlite
  signingStore:
    connection:
      type: sqlite
      database: signing_store.sqlite
  bootstrap:
    idps: []
    networks: []
