name: Build
on:
  - push
env:
  TARGET: ${{ github.ref == 'refs/heads/main' && 'wallet-gateway' || 'wallet-gateway-unstable' }}

jobs:
  Build:
    runs-on: digital-asset-wallet-gateway
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: version
        run: echo "version=$(<VERSION)" | tee -a "${GITHUB_OUTPUT}"
      - name: Docker Build
        uses: docker/build-push-action@v6
        with:
          build-args: version=${{ steps.version.outputs.version }}
          push: true
          tags: ghcr.io/digital-asset/${{ env.TARGET }}/docker/wallet-gateway:v${{ steps.version.outputs.version }}
