name: ci
on:
  - push

defaults:
  run:
    shell: nix-shell --run "exec bash -euo pipefail {0}"

jobs:
  check:
    runs-on: digital-asset-wallet-gateway
    permissions:
      contents: read
      issues: read
      checks: write
    steps:
      - uses: actions/checkout@v5
      - name: Check schema
        run: |
          make generate
          out="$(git status --porcelain)"
          if [ ! -z "${out}" ]; then
            echo "Helm schema needs to be re-generated, please run 'make generate'"
            echo "${out}"
            exit 1
          fi
          echo "No changes"
      - name: Helm unittests
        run: make test

  docker-build-and-publish:
    runs-on: digital-asset-wallet-gateway
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Generate outputs for downstream jobs
      - name: Versions
        id: versions
        uses: ./.github/actions/versions
      - name: Docker Tags
        id: tags
        uses: ./.github/actions/docker-tags
        with:
          registry-unstable: ghcr.io/digital-asset/wallet-gateway-unstable/docker
          registry-stable: ghcr.io/digital-asset/wallet-gateway/docker

        # Build first for testing (no publish): https://docs.docker.com/build/ci/github-actions/test-before-push/
      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        id: docker-export
        with:
          # Always use the stable version to pull down the npm package
          build-args: version=${{ steps.versions.outputs.stable }}
          load: true

      - name: Test container initializes successfully
        run: ./scripts/test-container-init.sh ${{ steps.versions.outputs.stable }} ${{ steps.docker-export.outputs.imageid }}

      # Setup buildx for multi-platform
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Actually publish the docker image
      - name: Docker Build and Publish
        uses: docker/build-push-action@v6
        with:
          build-args: version=${{ steps.version.outputs.version }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.tags.outputs.tags }}

  helm-publish:
    runs-on: digital-asset-wallet-gateway
    permissions:
      contents: read
      packages: write
    needs:
      - check
      - docker-build-and-publish
    steps:
      - uses: actions/checkout@v6

      - name: Helm Build and Publish
        uses: ./.github/actions/helm-build-push
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry-unstable: ghcr.io/digital-asset/wallet-gateway-unstable/helm
          registry-stable: ghcr.io/digital-asset/wallet-gateway/helm
